### PR TITLE
Enforce module attribute ordering

### LINKED ISSUE #540: Proposal: check use, import, alias, require having same order across files
Hi there! Thanks for package!
I didn't find rule to check order for directives: use, import, alias, require 
Wish it would be, to make code more consistent and prevent human mistakes
In future we can add option to set particular order, like `{Credo.Check.Readability.ModuleDirectivesOrder, order: [:use, :import, :require, :alias]}`

So, if you don't mind I'll try to implement this and do pull request

Here are examples:
- Valid
`use Ecto.Schema`
`import Ecto.Query`
`alias Ecto.Paging`
`require Logger`

- Also valid 
`import Ecto.Query`
`require Logger`

- Invalid
`require Logger`
`import Ecto.Query`
`alias Ecto.Paging`

What do you think?)

### PR DESCRIPTION
**Pull request by doomspork**
This attempts to close #540.  @rrrene I'd love to get your thoughts.  I'll work to refactor this to be a bit prettier.

### CODE REVIEW

**Comment by doomspork** [comment]
With @michaelstalker's help we've updated the rule to not only enforce the correct ordering of attribute types but that within each type, attributes are sorted alphabetically.

**Comment by doomspork** [comment]
I am _not_ applying this to the Credo codebase because there are a number of situations where Credo violates the community styleguide on this and I don't think we want that amount of code churn.

**Comment by rrrene** [comment]
@doomspork I just realized that I did not comment on this yet.

IMHO this should be a consistent check that points out inconsistencies in your ordering, i.e. raise an issue if you are following the community styleguide (or any other styleguide) and then you do not adhere to that order in a module.

WDYT?

**Comment by doomspork** [comment]
Good morning @rrrene!  I hope things are well with you and yours.

I think `consistency` is a good home for this.  Do you have any other thoughts?

**Comment by doomspork** [comment]
Updated 😁

**Comment by rrrene** [comment]
Hi, sorry for not replying earlier.

> If that's the case, we'll need to track every module's attributes order to assert this correct? 

Yep, that's what I wanted to say.

> Won't that be a bit cumbersome given the number of attributes and modules in larger projects?

Yep, that's why I want Credo to do it instead of keeping track myself 😄

**Comment by doomspork** [comment]
Wonderful @rrrene! I will be returning from holiday in a few days and intend to wrap these PRs up 👍

**Comment by Zeeker** [comment]
Hey there, what's the status on this? Can I be of any help? 🙂

**Comment by doomspork** [comment]
Howdy @Zeeker! Please do. I no longer work at RentPath and I'm not sure if they intend to continue work on this either. cc. @michaelstalker

**Comment by chevinbrown** [comment]
@rrrene what's the possibility of this being added? I'd be stoked to use credo instead of a style guide for module attributes. 😄

**Comment by sascha-wolf** [comment]
I'm not René but I plan on starting to work on this soon.

Kevin Brown <notifications@github.com> schrieb am Mo., 5. Aug. 2019, 22:38:

**Comment by doomspork** [comment]
Closing this as #747 did the job :+1:

**Pull request closed without merging**
