### PR TITLE
Replace return value of nil to return string in Module.name

### PR DESCRIPTION
**Pull request by sstern6**
This PR fixes: https://github.com/rrrene/credo/issues/201

### CODE REVIEW

**Comment by rrrene** [comment]
Superb. As always. :+1:

One thing: Can we have a test reproducing the old, broken behaviour to ensure it does not happen in the future?

**Comment by sstern6** [comment]
Thanks for the feedback @rrrene, on it and will repush!

**Comment by sstern6** [comment]
@rrrene let me know if you think the placeholder value `"<Unknown Module Name>"` should be changed to something else.

Thanks

**Comment by rrrene** [comment]
`"<Unknown Module Name>"` works perfect for now!

**Pull request merged**
