### PR TITLE
Test using OTP 19.0 also

### PR DESCRIPTION
**Pull request by gmile**

### CODE REVIEW

**Comment by rrrene** [comment]
Thx for the PR. Unfortunately Elixir < 1.2 does not support OTP 19. If you know of a config option that keeps Travis from failing that Elixir/OTP combination, please add it! :+1:

**Comment by gmile** [comment]
@rrrene added `matrix.exclude` to travis, this should be good now

**Comment by rrrene** [comment]
Perfect. Thx for your contribution :tada:

**Comment by gmile** [comment]
No problem! ❤️

**Pull request merged**
