### PR TITLE
Fix httpc error during credo version check

### LINKED ISSUE #223: Credo crashes with httpc error when starting
### Environment

* Credo version (`mix credo -v`): Unable to run as credo crashes but latest at the time of writing (cloned from git repo).
* Erlang/Elixir version (`elixir -v`): Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace], Elixir 1.3.4
* Operating system: Mac OS X 10.11.6

### What where you trying to do?

Run `mix credo`.

### Expected outcome

It runs.

### Actual outcome

```
$ mix credo
** (exit) exited in: :gen_server.call(:httpc_manager, {:request, {:request, :undefined, #PID<0.70.0>, 0, :https, {'hex.pm', 443}, '/api/packages/credo', [], :get, {:http_request_h, :undefined, 'keep-alive', :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, 'application/vnd.hex+erlang', :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, 'hex.pm', :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], 'Credo/0.5.2 (Elixir/1.3.4) (OTP/19)', :undefined, :undefined, :undefined, '0', :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, ...}, {[], []}, {:http_options, 'HTTP/1.1', :infinity, true, {:essl, []}, :undefined, false, :infinity, false}, 'https://hex.pm/api/packages/credo', [], :none, [], 1478865591843, :undefined, :undefined, false}}, :infinity)
    ** (EXIT) no process
    (stdlib) gen_server.erl:212: :gen_server.call/3
    httpc.erl:574: :httpc.handle_request/9
    lib/credo/check_for_updates.ex:66: Credo.CheckForUpdates.fetch/1
    lib/credo/check_for_updates.ex:59: Credo.CheckForUpdates.fetch_all_hex_versions/1
    lib/credo/check_for_updates.ex:4: Credo.CheckForUpdates.run/0
    lib/credo/cli.ex:92: Credo.CLI.run/1
    lib/credo/cli.ex:58: Credo.CLI.main/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
```

### PR DESCRIPTION
**Pull request by brienw**
Fixes #223

### CODE REVIEW

**Comment by sstern6** [comment]
👍 Thanks @brienw.

@rrrene might want to make a minor version bump and push a release to hex once this is in because im sure a lot of people are running into the problem shown on the linked issue.

**Comment by rrrene** [comment]
@brienw You're the man! :+1:

@sstern6 will do!

**Comment by rrrene** [comment]
@brienw `v0.5.3` contains your fix. Can you confirm that it works (when depending on the published version)?

**Comment by brienw** [comment]
@rrrene Just confirmed. Works as expected now, thanks for the release!

**Pull request merged**
