### PR TITLE
Replace deprecated functions for Elixir 1.5

### PR DESCRIPTION
**Pull request by leifg**
I came across a lot of compiler warning when testing out credo with Elixir 1.5

There is an easy fix, so I applied it

### CODE REVIEW

**Comment by leifg** [comment]
Oh just saw, this clashes with Elixir versions `< 1.3` I don't know what the guideline is. Shall old versions be supported? If yes, then I guess this cannot be merged.

**Comment by rrrene** [comment]
> There is an easy fix, so I applied it

I am afraid it's not that easy and I would really like to ensure backwards compatibility: https://travis-ci.org/rrrene/credo/builds/237500191?utm_source=github_status&utm_medium=notification

The only solution I see atm would be a "backports" module which uses the right functions at compile time. WDYT?

P.S. you already noticed this yourself. :wink:

**Comment by leifg** [comment]
Mmmh interesting, does something like that already exist?

**Comment by leifg** [comment]
OK I implemented a [backports library](https://github.com/leifg/backports) over the weekend. Tests run and the code is up to date.

What do you think?

**Comment by rrrene** [comment]
Hi, sorry for the delayed answer.

Unfortunately, when I wrote that I'd like to use a module here, I did mean to use a module. I would not want to have such a critical dependency in Credo and not have write access to the source code.

Furthermore, I think your Hex package tries to do too much. I quickly looked over the source code and there is some dark meta programming magic going on, which can easily break on future versions of Elixir, just like `v0.1.0` of `backports` demonstrated.

That said, I merged most of your commits by hand because your contribution is very valuable to this project, even without the last commit. :+1:

P.S. I also referenced two commits in this PR which show how I implemented the Backports module.

**Comment by leifg** [comment]
I see your point. I'm fine with the current implementation.

**Pull request closed without merging**
