### PR TITLE
Case sensitive alias order

### PR DESCRIPTION
**Pull request by kybishop**
This supercedes #1006 and addresses https://github.com/rrrene/credo/issues/1007

EDIT: @rrrene ignore earlier comment, I added support for alias grouping

### CODE REVIEW

**Comment by kybishop** [comment]
@rrrene I know you're busy so no worries, but let me know if you see any blockers for this when able and I'll get to them immediately.

**Comment by kybishop** [comment]
Would love to give a Christmas gift to all by shepherding this PR to the finish line. I'm not aware of any issues with the changes at the moment.

Let me know if there's anything preventing this from getting merged @rrrene

**Comment by rrrene** [comment]
Hi, sorry for being so unresponsive. Since this PR is actually two PRs, I simply have to find some quiet time to understand what is now proposed here and whether or not some of the things I find irritating about this is not the PRs fault, but is actually based in the current state of this check and ... Then OSS time is over for the weekend ... I will try to prioritze this Matroschka-PR :+1:

**Comment by kybishop** [comment]
@rrrene happy new year bump 🎉🎊🎉

**Pull request merged**
