### PR TITLE
Merge Code Climate Support

### PR DESCRIPTION
**Pull request by TreyE**
Add CodeClimate output support.

I found a branch of this which allowed outputting to CodeClimate format, however it was very out of date.  I have refactored this be against the latest 0.10.2 release.

This maybe should be offered as a merge against the release branch? - Is there such a branch?

### CODE REVIEW

**Comment by fazibear** [comment]
Is this just a copy of my PR? https://github.com/rrrene/credo/pull/592/files

**Comment by TreyE** [comment]
Yeah, I noticed your PR is against what seems to be an either a newer or the non-release version.  I was trying to make sure it could be merged into the current release version easily.  If you've already got a PR for that I'll kill this one.

**Comment by fazibear** [comment]
I'm maintaining a few patches to make `codeclimate-credo` works. Here is the issue: https://github.com/rrrene/credo/issues/591. I'm updating these to match the current version. Now they are 1.0 compatible.

**Comment by TreyE** [comment]
@fazibear It looks like you've got this rocking so I'll kill this one.

**Pull request closed without merging**
