### PR TITLE
fix: nested calling rule when interpolating in a string

### PR DESCRIPTION
**Pull request by yordis**

### CODE REVIEW

**Comment by yordis** [comment]
@rrrene, any feedback about the PR?

**Comment by rrrene** [comment]
Hi, thx for the fix. I merged it manually,

Unsure why this PR did not close automatically, your commit is here: https://github.com/rrrene/credo/commit/ba29ca1b80e4fd74b2599a972a968115199d7d47

I will close this manually. Great work :+1:

**Comment by yordis** [comment]
Hey @rrrene any opportunity to release this fix? 🙏🏻

**Comment by rrrene** [comment]
@yordis Sure. This is part of `1.7.2-rc.3` :+1:

**Pull request closed without merging**
