### PR TITLE
add Erlang/OTP 23 (latest) to CI matrix

### PR DESCRIPTION
**Pull request by adrianomitre**
Add last Erlang/OTP version to CI matrix and also upgrade minor Erlang/OTP 22 version and Elixir 1.7 patch version.

Warning: there are some combinations (none added by this pull request) that are not compatible according to [Compatibility and Deprecations — Elixir v1.10.3](https://hexdocs.pm/elixir/compatibility-and-deprecations.html) (e.g., Elixir 1.9 & Erlang/OTP 23), but @rrrene [disapproved](https://github.com/rrrene/credo/pull/785#issuecomment-659462251) the [non-cartesian-product approach](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-new-combinations) to Elixir × Erlang/OTP version matrix, so I am waiting for him to suggest a workaround more to his liking. Maybe using the cartesian approach + [exclusion](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-excluding-configurations-from-a-matrix) for filtering?

This pull request was extracted (deformed) from https://github.com/rrrene/credo/pull/785.

### CODE REVIEW

**Comment by rrrene** [comment]
I will apply some of the suggested changes from your 7 PRs. Thx. :+1:

> This pull request was extracted (deformed) from #785.

As a side note: I am a non-native speaker of english myself and I have chosen the wrong words in the past without realising it. So please take this advice: 

Please think about how your actions and words can be perceived. When a PR to an open source project gets rejected (which happens to all of us, for various reasons) and as a consequence, you open up 7 new PRs containing words like "[the maintainer] disapproved the non-cartesian-product approach" and "this pr was deformed" than the picture you are projecting might not be a content, calm and humble one.

It might come off the wrong way and everything here is probably well intended. but we are never in control of how our words and actions will be perceived.

*note:* I will close the others and link back to this.

**Comment by adrianomitre** [comment]
I do not want to jump to conclusions, but it was not clear why you replicated my pull request in a [commit of your authoring](https://github.com/rrrene/credo/commit/db2248508c1cf050d5e3aa6f1a58fcbb1a80946f) instead of simply merging this PR (which would be simpler for you, by the way).

**Comment by rrrene** [comment]
Please refer to my other comment in one of the other PRs ...

I'd like to repeat myself:

> Please think about how your actions and words can be perceived.

Insinuating that I am "stealing" something from you is insulting to say the least.

**Comment by adrianomitre** [comment]
Please refer to https://github.com/rrrene/credo/pull/796#issuecomment-660742454

**Pull request closed without merging**
