### PR TITLE
Elixir 1.13 support

### PR DESCRIPTION
**Pull request by hypno2000**
related to https://github.com/rrrene/credo/issues/893

https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_tokenizer.erl#L154

### CODE REVIEW

**Comment by BartOtten** [comment]
Works as expected. Thanks

**Comment by rrrene** [comment]
@hypno2000  Thx!

**Comment by v0idpwn** [comment]
As of https://github.com/elixir-lang/elixir/pull/11315 the format changed to `{ok, Line, Column, Warnings, Tokens}`

**Comment by rrrene** [comment]
@v0idpwn not at home right now. could you open a PR?

**Pull request merged**
