### PR TITLE
Allow passing a list of files to `mix credo`

### PR DESCRIPTION
**Pull request by tzzzoz**
Initial implementation for #332

### CODE REVIEW

**Comment by rrrene** [comment]
@tzzzoz Thanks for putting this together. :+1:

Unfortunately, this PR has far reaching consequences, as it allows me to analyse multiple directories, which could contain multiple `.credo.exs` files, which might have consequences I can not foresee in the moment.

I will have to think about this, but this is not likely to be included before `v1.0`. But your PR is very helpful in answering these questions with a present implementation. Thx!

**Comment by tzzzoz** [comment]
Thanks for your feedback, I understand your concern, let me know if I can help.

**Comment by jacknoble** [comment]
@rrrene Perhaps there should be a cli option to specify a path to a `.credo.exs` file (`mix credo --config_path=~/.credo.exs`). This makes sense as a feature by itself but it could also be used to support running credo on a list of files. And running on a list of files could be prohibited without supplying a `config_path`.

**Comment by rrrene** [comment]
@jacknoble Not sure about that. So it would use the `:files` from that `.credo.exs`, but execute in the current directory?

**Comment by jacknoble** [comment]
That would be the idea. The :files thing could be confusing, I guess.

**Comment by rrrene** [comment]
Hi, thx again for this. Unfortunately, I am closing it due to "it being obsolete" IMHO. 

If you disagree, please re-open and elaborate! :+1:

**Pull request closed without merging**
