### PR TITLE
Add codeclimate output format

### PR DESCRIPTION
**Pull request by fazibear**
Part of work related to https://github.com/rrrene/credo/issues/591

Add output format for codeclimate checker.

### CODE REVIEW

**Comment by larkinscott** [comment]
@rrrene Sorry to bother you again and thanks for your reply on: https://github.com/rrrene/credo/pull/595#issuecomment-573428600

I think we'd still want to get this formatter merged in to get the `codeclimate-credo` plugin working without needing to maintain a fork of `credo` itself. I see some conflicts but am happy to get them cleaned up or open a new PR if that helps. Thanks again!

**Comment by rrrene** [comment]
@larkinscott I really appreciate that there is a CodeClimate integration for Credo as much as, say, SourceLevel's (formerly Plataformatec's Ebert). That being said, merging a single provider's format into Credo's own source code seems odd. For example, having the mapping of specific Credo checks to CodeClimate categories hard-wired inside Credo would tightly couple two otherwise unrelated software projects.

`---format json` should expose all the necessary information to write an external "adapter" (that maps Credo's JSON to whatever the integration needs). 

Maybe you can elaborate why you have to maintain a fork of Credo for your integration with CodeClimate?

**Comment by NobbZ** [comment]
Going from `--format json` and reformatting it into whatever an adapter needs seems to be a nice thing, though it requires to do the work in another OS-process.

Have you considered `--formatter Formatter` where `Formatter` is a module that implements a behaviour?

`--format json` would still be available for those that prefer to deal with JSON in language X, but also through the formatter option those that want to use Elixir or Erlang get real advantage as they can get all the tools they like and you could even provide library functions later on that help dealing with formatting related stuff.

**Comment by rrrene** [comment]
> Have you considered `--formatter Formatter` where `Formatter` is a module that implements a behaviour?

Yes and no. 😄 We'll have to discuss how plugins, introduced in `v1.1` and enhanced in the upcoming `v1.2` can provide both additional as well as different formatting to existing checks (e.g. both new formats like YAML as well as modify the existing output for built-in commands).

But that does not concern the issue discussed here, which is to merge CodeClimate specific code into Credo. :+1:

**Comment by larkinscott** [comment]
@rrrene Good point. In fact, most of our other plugins work this way. I'm not super familiar with the credo codebase so I was just sort of following the pattern this PR set, but I can tweak our plugin to work with credo's JSON output instead. Thanks again!

**Comment by rrrene** [comment]
@larkinscott To expand on @NobbZ's point: You can also run Credo "natively" from your Elixir project `codeclimate-credo` by adding `credo` as a  dependency and invoking [`Credo.CLI.run(argv)`](https://github.com/rrrene/credo/blob/d1e3a56f07f96203d86d6416cefbccbd8684ea13/lib/credo/cli.ex#L24) with `argv` being the command line arguments you would provide. The function returns the found `%Credo.Issue{}` structs. :+1:

**Pull request closed without merging**
