### PR TITLE
Badge with current version and link to package

### PR DESCRIPTION
**Pull request by PragTob**
Always find this to be nice to have around, so one can quickly see what the most current version is. Unsure about the positioning among badges, I like it to be first but didn't want to impose my views :)

### CODE REVIEW

**Comment by rrrene** [comment]
Sure! Can you put a space between the docs badge and the version badge?

**Comment by PragTob** [comment]
most certainly, sorry! :)

**Comment by PragTob** [comment]
done!

**Comment by rrrene** [comment]
Aaand it's merged! :grin:

**Pull request merged**
