### PR TITLE
add `nil_else` check for else blocks containing only `nil`

### PR DESCRIPTION
**Pull request by zachdaniel**
Adds a check that will fail on an `else` block containing only `nil`.

### CODE REVIEW

**Comment by OvermindDL1** [comment]
Ehh, not a fan of that.  If anything there should be a  check on `if`'s containing no `else` block.  Shouldn't rely on a missing `else` being `nil` as it makes it very easy to skip over visually.

**Comment by zachdaniel** [comment]
@OvermindDL1 I agree :) I wouldn't personally enable this check. However, it appears on https://github.com/lexmag/elixir-style-guide this style guide, and I'm working w/ a client that follows it. I figured we could just have it disabled by default.

**Comment by OvermindDL1** [comment]
Heh, as long as it's not default enabled or so, including 'hidden' pathways like that I find to be very bad for maintainability...  ^.^;

**Comment by zachdaniel** [comment]
Yeah, I see where you are coming from. I think that style guide is fairly popular though, so I don't think it would be the kind of thing that no one uses for two years and then someone tries it and it doesn't work 🤣

**Comment by OvermindDL1** [comment]
\<bikeshedding>

> _I think that style guide is fairly popular though_

_Well Elixir also encourages using spaces for indentation and alignment instead of [tabs for indentation and spaces for alignment](http://lea.verou.me/2012/01/why-tabs-are-clearly-superior/), so not all popular things are good.  ^.^_

\</bikshedding>

But I think that style guide basically died when the official formatter came out.  It does still specify some things that the formatter doesn't since the formatter won't change the AST, but I haven't seen anyone link to it in well over a year now.  ^.^;

**Comment by zachdaniel** [comment]
I think credo has a config file for exactly this reason though, to allow toggling these on and off. I could see a case for having a separate repo that just contains checks that exist to conform to the style guide, that way general users only get the "curated" checks that the maintainers think are worthwhile. But since its so easy to leave them off and just let people use them as the please it doesn't seem harmful really.

**Comment by OvermindDL1** [comment]
I personally don't see any problem including them in credo, disabled by default when conflicting like this one.  Credo could have a special section for them in the config documented as for the purposes of the style guide at that link perhaps?

**Comment by zachdaniel** [comment]
Yeah, I was thinking it could be nice to have some kind of switch/tag that says "enable all the lexmag style guide checks" or something like that.

**Comment by whatyouhide** [comment]
I very strongly disagree with this check as I find that when `if` is used without an `else` to leverage the implicit `nil` the code becomes much harder to read. However, maybe the compromise here is to have an option that decides what style you prefer? Maybe it can default to forcing an `else` if the return value of `if` is used, but at least having an option everyone's happy :(

**Comment by zachdaniel** [comment]
I think that what you’re suggesting now should be a separate check, and you can enable this, that, or neither.  I do agree though, I’d rather see an else w/ a nil honestly.``

**Comment by zachdaniel** [comment]
But this implementation is to support a specific style guide, so even though I’m not a fan, I’d still like to see it as an option.

**Comment by rrrene** [comment]
I'm closing this for now, as I think these checks should probably live in a plugin.

As for this specific check: I don't think giving people a tool to force writing less explicit code is a good idea.

**Pull request closed without merging**
